### ISSUE TITLE
Crashes when I click stop

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/ror-server#11]
When I want to stop my server, the program crashes when I click stop. My server version is RoRnet_2.37. Not sure if there is a newer version.

**Comment by Hiradur** [comment]
That's the protocol version not the server version. Where did you get it from? To make sure it's the newest version you can compile it yourself.

**Comment by gigapouch** [comment]
I think I got it from here: https://sourceforge.net/projects/rorserver/

**Comment by Hiradur** [comment]
Are you using Windows? Can you compile from source?
