### ISSUE TITLE
Rigs Of Rods Linux Server Will Not Stay Running for more than 25 seconds when the masterserver is not working.

### ISSUE THREAD

**Issue by Chris7676** [RigsOfRods/ror-server#13]
So I have tried a month ago to start my RoR Multiplayer Server running on Linux, Ever since the master server has had issues during the transition to only-a-ptr. Actually a few weeks after they said they were backing up the forum. Which was when the issue was opened in the official repo. (That issue was opened by DirtGamer30). So ever since then my 2 RoR servers I run will not stay running for more than 25 seconds. They just stop. There is no error in the putty session for the servers. My bot on IRC just says ERRR Connecting.

**Comment by Hiradur** [comment]
You have to run them in LAN mode until the master server is running again.

**Comment by chris7676** [comment]
I use a hostname. And I put LAN in the config and I don't even get a start message.

**Comment by Hotrod55** [comment]
The only difference between internet and LAN mode is that LAN mode doesn't attempt to connect to the master server. It should log `Server started in LAN mode.`

**Comment by Chris7676** [comment]
Do I need to comment out the webserver. Or just put n for webserver support? Because when I run etc/init.d/rorserver start nothing happens. And there is nothing in the log.

**Comment by Hotrod55** [comment]
Just put n, the webserver isn't finished at all. And if the etc/init.d/rorserver script doesn't work, try to start it directly from the bin directory. (For example, this will start a server using a config file: `./rorserver -c "/path/to/config.cfg"`

**Comment by Chris7676** [comment]
root@vps201793:/etc/rorserver# ./rorserver -c "/etc/rorserver/simple.cfg"                                                                                                                                                                 
bash: ./rorserver: No such file or directory

**Comment by Hotrod55** [comment]
If you ran `make install`, the `rorserver` binary should be located in /usr/bin/
Run the command in that directory.

**Comment by Chris7676** [comment]
aha. Thankyou. It worked!

**Comment by Hotrod55** [comment]
Glad to help :smile: You can close this issue now.
