### ISSUE TITLE
can not get an ip.

### ISSUE THREAD

**Issue by themienrgaming** [RigsOfRods/ror-server#25]
i just can not get an ip it said fail

**Comment by only-a-ptr** [comment]
That means you didn't specify your public IP and ror-server failed to auto-detect it.

The auto-detection requires our master server (https://github.com/only-a-ptr/multiplayer.rigsofrods.org) to be online, which isn't true yet.

You can test the gameserver->masterserver interaction by installing our masterserver locally. You'll need to install webserver+database, (use [XAMPP](https://www.apachefriends.org/index.html) if you're on windows) and configure the gameserver to look for masterserver on your localhost.

**Comment by themienrgaming** [comment]
how

**Comment by AnotherFoxGuy** [comment]
>The auto-detection requires our master server (https://github.com/only-a-ptr/multiplayer.rigsofrods.org) to be online, which isn't true yet.

The master server is online actually (http://multiplayer.rigsofrods.org/server-list/ && http://multiplayer.rigsofrods.org/get-public-ip/)
But it returns
```
!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
```

**Comment by only-a-ptr** [comment]
Oh, I didn't know you installed it. Just tried - getting the IP is working for me.

**Comment by themienrgaming** [comment]
well i got the ip but do i past the ip in?
