### ISSUE TITLE
Server crashes with lots of player traffic?

### ISSUE THREAD

**Issue by DevRain2500** [RigsOfRods/ror-server#34]
I'm not sure if this is the actual cause of it, but the server seems to just crash when there is a lot of player traffic at one time.

I am attaching the logfile with the max verbosity so you can see what it says.

[MM_server-log_file.txt](https://github.com/RigsOfRods/ror-server/files/614009/MM_server-log_file.txt)

**Comment by Michael10055** [comment]
I have the same issue. After the server reached 9/15 players, the server crashed. Decreasing the player limit to 8 seemed to have helped. Although the server will shut down if the heartbeat fails after 5 tries, I did increase the heartbeat limit to see if it'll change anything.

**Comment by Dogy144** [comment]
@Michael10055 I had managed to get my server up to 12/16 players without crashing, but it seemed to have crashed the clients out until getting back to 9 players and then crashing entirely. It is a very strange thing.
