### ISSUE TITLE
Crash with current master: bad UTF-8 continuation byte

### ISSUE THREAD

**Issue by DevRain2500** [RigsOfRods/ror-server#37]
Server log shows this error, and then rorserver.exe crashes. (Windows Server 2012 R2)

```
15-01-2017 17:00:09|t03| INFO| UTF conversion error: bad UTF-8 continuation byte
15-01-2017 17:00:09|t03|ERROR| (UTF conversion error 2)
```

**Comment by only-a-ptr** [comment]
Many thanks for reporting! I wasn't even aware this can happen within the rorserver, but apparently I [missed](https://github.com/RigsOfRods/ror-server/blob/1152367d1f6beb492f4ac780809f322b4a838e3c/source/server/UTFString.cpp#L1916) [something](https://github.com/RigsOfRods/ror-server/blob/1152367d1f6beb492f4ac780809f322b4a838e3c/source/server/UTFString.cpp#L1813)

Please set `verbosity = 0` in your config file, try again and post the log. I'd like to see where the faulty data are coming from.

But anyway, I'm going to sanitize all incoming data for correct UTF-8

**Comment by Dogy144** [comment]
That error output is with `verbosity = 0` already.

**Comment by only-a-ptr** [comment]
@Dogy144 Can you post the whole log then?
Also, what is your system default locale? What language is your Windows Server running with?

**Comment by Dogy144** [comment]
Full log:
```
17-01-2017 18:08:38|t01| INFO| loading config file ../settings/server.cfg ...
17-01-2017 18:08:38|t01| INFO| server started in LAN mode.
17-01-2017 18:08:38|t01| INFO| port:       12234
17-01-2017 18:08:38|t01| INFO| terrain:    any
17-01-2017 18:08:38|t01| INFO| maxclients: 8
17-01-2017 18:08:38|t01| INFO| server is NOT password protected
17-01-2017 18:08:38|t02|DEBUG| Listerer thread starting
17-01-2017 18:08:38|t03|DEBUG| Killer thread ready
17-01-2017 18:08:38|t03|DEBUG| Killer entering cycle
17-01-2017 18:08:38|t02|VERBO| Listener ready
17-01-2017 18:08:38|t02|VERBO| Listener awaiting connections
17-01-2017 18:08:38|t01|DEBUG| LAN broadcast successful
17-01-2017 18:08:38|t02| INFO| UTF conversion error: bad UTF-8 continuation byte
17-01-2017 18:08:38|t02|ERROR| (UTF conversion error 2)
```
System Locale: United States
Language: English (US)
