### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nickbus60** [RigsOfRods/ror-server#42]
here is the log 
03-04-2017 15:59:17|t01| INFO| Starting server in INET mode
03-04-2017 15:59:17|t01| INFO| IP address: 192.168.0.55
03-04-2017 15:59:17|t01| INFO| Maximum required upload: 15360kbit/s
03-04-2017 15:59:17|t01| INFO| Maximum required download: 1024kbit/s
03-04-2017 15:59:17|t01| INFO| Server name: [2.38] first student
03-04-2017 15:59:17|t01| INFO| server started in Internet mode.
03-04-2017 15:59:17|t01| INFO| port:       12000
03-04-2017 15:59:17|t01| INFO| terrain:    any
03-04-2017 15:59:17|t01| INFO| maxclients: 16
03-04-2017 15:59:17|t01| INFO| server is password protected
03-04-2017 15:59:17|t01| INFO| Attempting to register on serverlist (//server-list)
03-04-2017 15:59:20|t01| INFO| Registration failed, response code: HTTP 503, body: {"result":false,"message":"Could not connect to your server and verify it's version. Please check your Firewall or leave it as it is now to create a local only server. Your server is NOT

**Comment by Strykr1** [comment]
Your IP Address is wrong. Leave the IP address blank section blank in your
ror config.

**Comment by Strykr1** [comment]
Your IP Address is wrong. Leave the IP address blank section blank in your ror config.

**Comment by nickbus60** [comment]
i dont know
