### ISSUE TITLE
Allow visitors to multiplayer servers to see which terrain each person is on

### ISSUE THREAD

**Issue by LNFWebsite** [RigsOfRods/ror-server#43]
This is a feature request.

I always find myself asking on the chat what map everyone is using, and I know I'm not the only one because others have asked me. It would be nice to be able to see the terrains which each user is on (possibly using a ping command in the chat or something like this).

Thanks ahead!

**Comment by only-a-ptr** [comment]
Hmm... I suppose this refers to servers with "map=any" setting. TBH I don't even know how those work - do you only see other players when you spawn the same map? From what I recall of `rorserver` codebase, this shouldn't be possible. But I guess it somehow works.

**Comment by DevRain2500** [comment]
In multiplayer, when a server is set to `any` You can still see other players if they are on another terrain. Most of the time you can see them floating in the air or below your loaded terrain.

**Comment by only-a-ptr** [comment]
@DevRain2500 🤣 So my observation was correct. Thanks!

@LNFWebsite The request makes perfect sense. But IIRC the server doesn't know what terrain an individual player is on. And since it all works in such a clunky manner as DevRain described, I'd rather decomission the whole "any" option than doing extra development to support it.

**Comment by Michael10055** [comment]
One of Neorej16's scripts can output the current terrain list with a command (`!tlist`). But it won't work on the latest versions since Angelscript support is broken:
![mirc_2017-04-18_21-16-57](https://cloud.githubusercontent.com/assets/11002490/25159268/ae8c35e2-247c-11e7-82f6-f5fe6838ac89.png)

**Comment by LNFWebsite** [comment]
@only-a-ptr @DevRain2500 @Michael10055 

Yeah, sorry I didn't make that clear...

Most of the multiplayer servers listed in the in-game list are for "any" terrain and it becomes annoying asking every person which terrain they are on.

You can almost always see their vehicles, yet they are placed somewhere randomly, going over hills and roads that are completely non-existent for you.

If there was some sort of command, or like you said, restriction to a single terrain, this would work almost flawlessly...

Thanks for taking the time to look into this!

**Comment by Michael10055** [comment]
I'm closing this as the functionality is already provided by scripts.

**Comment by LNFWebsite** [comment]
@Michael10055 Quick question... Will the command !tlist work on most of the official RoR multiplayer servers?

Thanks ahead!

**Comment by Michael10055** [comment]
Yes, the command works on all official RoRNet 2.38 servers.

**Comment by LNFWebsite** [comment]
@Michael10055 Okay, thanks!
