### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by nickbus60** [RigsOfRods/ror-server#51]
![image](https://user-images.githubusercontent.com/18500535/38994596-d2baf22a-43b4-11e8-83a8-71996f3cd2cb.png)
![image](https://user-images.githubusercontent.com/18500535/38994677-07b18a02-43b5-11e8-8fd1-bd63cc144f61.png)
what could be causing that?

**Comment by Michael10055** [comment]
It seems like Angelscript is currently broken on the latest master. Just recompile the server without Angelscript support.

**Comment by nickbus60** [comment]
how would do that?
