### ISSUE TITLE
Sending chat message results in crash 

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/ror-server#60]
On Windows, sending a chat message will cause the server to crash.
VS debug output:
![image](https://user-images.githubusercontent.com/46073351/51444167-1ef33800-1cc2-11e9-8088-63a886239d50.png)
It doesn't crash on Linux, but the chat log outputs a bunch of garbage characters:
![image](https://user-images.githubusercontent.com/46073351/51444182-5366f400-1cc2-11e9-8c2a-f52a8283e1a4.png)

**Comment by ulteq** [comment]
That one is fixed, right?

**Comment by ulteq** [comment]
Fixed with: https://github.com/RigsOfRods/ror-server/pull/61
