### ISSUE TITLE
Server Log Not Updating

### ISSUE THREAD

**Issue by RyGuy0248** [RigsOfRods/ror-server#91]
I am hosting a 0.4.8 server. I'm attempting to open my log file but all I can see is the startup lines (loading config, server started, port: xxx, etc). It doesn't update. Any clue?

**Comment by Zentro** [comment]
Lol, June 19th.

It'll fork in the background under the `rorserver` user. If you're using a panel like Pterodactyl, make sure to have the `-fg` argument in your startup command. `./rorserver -c server.cfg -fg`.

**Comment by tritonas00** [comment]
any update, @RyGuy0248 ?

**Comment by RyGuy0248** [comment]
I just decided to run it in a Screen session in the foreground. All of the details came up.
